# Generated by Django 3.2.7 on 2021-10-04 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='total_amount_invested',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='total_investement_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='uri',
            field=models.CharField(blank=True, default='4456687724', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='wallet_id',
            field=models.CharField(default='6AE5E54DD0', max_length=50, unique=True),
        ),
    ]
