# Generated by Django 3.2.7 on 2021-10-05 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20211004_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='uri',
            field=models.CharField(blank=True, default='14340A55A2', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='wallet_id',
            field=models.CharField(default='B942E49D6C', max_length=50, unique=True),
        ),
    ]
