# Generated by Django 3.2.7 on 2021-10-05 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20211005_0540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='uri',
            field=models.CharField(blank=True, default='886D53E01F', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='wallet_id',
            field=models.CharField(default='AF26561EFC', max_length=50, unique=True),
        ),
    ]
