# Generated by Django 3.2.7 on 2021-10-04 13:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trans_type', models.CharField(max_length=50)),
                ('amount_in_coin', models.FloatField(blank=True, null=True)),
                ('amount_in_usd', models.IntegerField(blank=True, null=True)),
                ('coin_tpye', models.CharField(max_length=50)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('uri', models.CharField(default='CBA07E2DA1C54F9FA9AD3C16119625', max_length=50)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_transactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='POP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_in_coin', models.FloatField(blank=True, null=True)),
                ('amount_in_usd', models.IntegerField(blank=True, null=True)),
                ('coin_tpye', models.CharField(max_length=50)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('approved_dated', models.DateTimeField(blank=True, null=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('uri', models.CharField(default='D253A8A81DC741E09BA3EB275FAF77', max_length=50)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_pop', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Investments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_invested', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('is_complete', models.BooleanField(default=False)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('crediting_date', models.DateTimeField(blank=True, null=True)),
                ('amount_earn', models.IntegerField(default=0)),
                ('uri', models.CharField(default='2CBB8008710A477785DBC225DF7EEB', max_length=50)),
                ('pop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='investment_pop', to='crypto_app.pop')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
