# Generated by Django 3.2.7 on 2021-10-04 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investments',
            name='uri',
            field=models.CharField(default='5BBEF71C09F043F6AAC5C3869440DA', max_length=50),
        ),
        migrations.AlterField(
            model_name='pop',
            name='uri',
            field=models.CharField(default='3F547B98DBC2413E814D5C2BD6D889', max_length=50),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='uri',
            field=models.CharField(default='65076C03FAA84C8D831311A358DC30', max_length=50),
        ),
    ]
