# Generated by Django 3.2.7 on 2021-10-04 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_app', '0004_auto_20211004_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investments',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('inactive', 'inactive'), ('pending', 'pending'), ('complete', 'completed')], default='inactive', max_length=40),
        ),
        migrations.AlterField(
            model_name='investments',
            name='uri',
            field=models.CharField(default='6BD46FFF034F4A9BB5D350212B52D9', max_length=50),
        ),
        migrations.AlterField(
            model_name='pop',
            name='uri',
            field=models.CharField(default='F6D67EA74A6A4EEBB31C81290129FA', max_length=50),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='uri',
            field=models.CharField(default='8FA208BA4F454EBAB0C08749A71206', max_length=50),
        ),
    ]
