# Generated by Django 3.2.7 on 2021-10-05 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_app', '0007_auto_20211005_0635'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='investments',
            name='uri',
            field=models.CharField(default='AC26BB752EBC41F798F30BBBAEEAD9', max_length=50),
        ),
        migrations.AlterField(
            model_name='pop',
            name='uri',
            field=models.CharField(default='A362AEA1EE35451D823C8D9F2479F0', max_length=50),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='uri',
            field=models.CharField(default='813529306CC3468AA0248DAFDA804A', max_length=50),
        ),
    ]
